<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict //EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
	<title>ATutor 1.5 Instructor Documentation</title>
	<link rel="stylesheet" href="../styles.css" type="text/css" />
</head>
<body>


<div class="nifty"><b class="rtop"><b class="r1"></b><b class="r2"></b><b class="r3"></b><b class="r4"></b></b>
	<h1>5.0 Enrollment</h1>
	<p>The student list for a particular course determines which of your students have access to the course content. ATutor has the facility to allow instructors to create, import and export student lists. </p>
	
	<p>To administer the users in your course, you need to be logged in as the instructor and have selected the <em>Enrollment</em> option from the <em>Manage</em> tab.</p>

	<h3>Table of Contents</h3>
	<div id="toc">
		<ul>
			<li>5.1 <a href="#5.1">Creating, Importing, and Exporting Course Lists</a></li>
			<ul>
				<li>5.1.1 <a href="#5.1.1">Creating a Course List</a></li>
				<li>5.1.2 <a href="#5.1.2">Creating a Course Enrollment List for Import</a></li>
				<li>5.1.3 <a href="#5.1.3">Importing Course Enrollment Lists</a></li>
				<li>5.1.4 <a href="#5.1.4">Exporting Course Enrollment Lists</a></li>
			</ul>
			<li>5.2 <a href="#5.2">Groups, Roles & Privleges</a></li>
			<ul>
			<li>5.2.1 <a href="#5.2.1">Groups</a></li>
			<li>5.2.2 <a href="#5.2.2">Roles & Privleges</a></li>
			</ul>
			<li>5.3 <a href="#5.3">Un-enroll, Alumni</a></li>
		</ul>
	</div>
<b class="rbottom"><b class="r4"></b><b class="r3"></b><b class="r2"></b><b class="r1"></b></b></div>

<div class="nifty"><b class="rtop"><b class="r1"></b><b class="r2"></b><b class="r3"></b><b class="r4"></b></b>

<a name="5.1"></a><h2>5.1 Creating, Importing, and Exporting Course Lists</h2>

<a name="5.1.1"></a><h3>5.1.1 Creating a Course List</h3>
<p>You have the option of manually generating the student list by selecting the <em>Create Course List</em> option. This option is useful if you have a small number of students to add to a course, but if you have many students to enlist then the <em>Import</em> feature may be a more efficient option.</p>

<a name="5.1.2"></a><h3>5.1.2 Creating a Course Enrollment List for Import</h2>
<p>To import a list as a file from your local system to ATutor, the enrollment list should follow the format specified by your administrator. By default, the format for the list is <kbd>"firstname", "lastname", "email"</kbd> with one student per line, but your administrator may have a different format.</p>

<p>Such lists can be easily generated by programs like a spreadsheet, or a database. Once you have the list as a file, you are ready to import it into ATutor.</p>

<a name="5.1.3"></a><h3>5.1.3 Importing Course Enrollment Lists</h2>
<p>To import a list of students into your course, you must first have a file on your local computer containing all the necessary information. To import a course list, select the <em>Import Course List</em> link and then select the file on your system by using the <kbd>Browse</kbd> button. Finally select the <kbd>Import Course List</kbd> button to upload the list to ATutor.</p>

<p>When importing an enrollment list, ATutor will automatically generate user names based on the firstnames and lastnames. You have the option of seperating the username using an underscore or a period. (i.e. John_Smith, or John.Smith).</p>

<a name="5.1.4"></a><h3>5.1.4 Exporting Course Enrollment Lists</h2>
<p>A course enrollment list can be exported from ATutor which is useful as a backup or for importing into other courses. You can select subsets of students to export (enrolled students, un-enrolled students, and alumni). Selecting <kbd>Export</kbd> will begin a download in your browser. The exported list is in comma-seperated format.</p>
<b class="rbottom"><b class="r4"></b><b class="r3"></b><b class="r2"></b><b class="r1"></b></b></div>

<div class="nifty"><b class="rtop"><b class="r1"></b><b class="r2"></b><b class="r3"></b><b class="r4"></b></b>
<a name="5.2"></a><h2>5.2 Groups, Roles & Privleges</h2>
<a name="5.2.1"></a><h3>5.2.1 Groups</h3>
<p>Students can be placed into groups which allows the instructor administer different tests to different groups.</p>

<a name="5.2.1"></a><h3>5.2.2 Roles & Privleges</h3>
<p>Each student in your course can be assigned a role and special administrative privleges. This allows some (or all) of your students to perform actions like manage the glossary, or administer the forums.</p>

<p>Roles act as labels for assigned students.</p>
<b class="rbottom"><b class="r4"></b><b class="r3"></b><b class="r2"></b><b class="r1"></b></b></div>

<div class="nifty"><b class="rtop"><b class="r1"></b><b class="r2"></b><b class="r3"></b><b class="r4"></b></b>
<a name="5.3"></a><h2>5.3 Un-enroll, Alumni</h2>
<p>Once a student has been enrolled, it is possible to remove them from being enrolled in the class. Alternatively, students on the un-enrolled list can be enrolled in the course by selecting the student(s) and then selecting <kbd>Enroll</kbd>.</p>

<p>Whether a student is on the <em>Enrolled</em> or <em>Un-enrolled</em> list, you can designate one or more students as an alumni of the course. This gives them access to all course content with the exception of the forums and tests/surveys.</p>

<b class="rbottom"><b class="r4"></b><b class="r3"></b><b class="r2"></b><b class="r1"></b></b></div>

</body>
</html>