<?php require('../common/body_header.inc.php'); ?>

<h2>6.4 Course Lists</h2>

<h3>6.4.1 Creating a Course List</h3>
<p>You have the option of manually generating the student list by selecting the <em>Create Course List</em> option. This option is useful if you have a small number of students to add to a course, but if you have many students to enlist then the <em>Import</em> feature may be a more efficient option.</p>

<h3>6.4.2 Creating a Course Enrollment List for Import</h3>
<p>To import a list as a file from your local system to ATutor, the enrollment list should follow the format specified by your administrator. By default, the format for the list is <kbd>"firstname", "lastname", "email"</kbd> with one student per line, but your administrator may have a different format.</p>

<p>Such lists can be easily generated by programs like a spreadsheet, or a database. Once you have the list as a file, you are ready to import it into ATutor.</p>

<h3>6.4.3 Importing Course Enrollment Lists</h3>
<p>To import a list of students into your course, you must first have a file on your local computer containing all the necessary information. To import a course list, select the <em>Import Course List</em> link and then select the file on your system by using the <kbd>Browse</kbd> button. Finally select the <kbd>Import Course List</kbd> button to upload the list to ATutor.</p>

<p>When importing an enrollment list, ATutor will automatically generate user names based on the firstnames and lastnames. You have the option of seperating the username using an underscore or a period. (i.e. John_Smith, or John.Smith).</p>

<h3>6.4.4 Exporting Course Enrollment Lists</h3>
<p>A course enrollment list can be exported from ATutor which is useful as a backup or for importing into other courses. You can select subsets of students to export (enrolled students, un-enrolled students, and alumni). Selecting <kbd>Export</kbd> will begin a download in your browser. The exported list is in comma-seperated format.</p>

<?php require('../common/body_footer.inc.php'); ?>