<?php
/****************************************************************/
/* ATutor														*/
/****************************************************************/
/* Copyright (c) 2002-2003 by Greg Gay & Joel Kronenberg        */
/* Adaptive Technology Resource Centre / University of Toronto  */
/* http://atutor.ca												*/
/*                                                              */
/* This program is free software. You can redistribute it and/or*/
/* modify it under the terms of the GNU General Public License  */
/* as published by the Free Software Foundation.				*/
/****************************************************************/


function write_config_file($filename, $comments) {

	global $config_template;

	$tokens = array('{USER}',
					'{PASSWORD}',
					'{HOST}',
					'{PORT}',
					'{DBNAME}',
					'{ADMIN_PASSWORD}',
					'{ADMIN_EMAIL}',
					'{EMAIL_NOTIFY}',
					'{INSTRUCTOR_REQUESTS}',
					'{APPROVE_INSTRUCTORS}',
					'{MAX_FILE_SIZE}',
					'{MAX_COURSE_SIZE}',
					'{MAX_COURSE_FLOAT}',
					'{ILL_EXT}',
					'{SITE_NAME}',
					'{TABLE_PREFIX}',
					'{BACKWARDS_COMPATIBILITY}',
					'{GENERATED_COMMENTS}');

	if ($_POST['step1']['old_path'] != '') {
		require('../../'.$_POST['step1']['old_path'] . '/include/config.inc.php');
		$values = array(DB_USER,
					DB_PASSWORD,
					DB_HOST,
					defined('DB_PORT') ? DB_PORT : 3306,
					DB_NAME,
					ADMIN_PASSWORD,
					ADMIN_EMAIL,
					EMAIL_NOTIFY ? 'TRUE' : 'FALSE',
					ALLOW_INSTRUCTOR_REQUESTS ? 'TRUE' : 'FALSE',
					AUTO_APPROVE_INSTRUCTORS ? 'TRUE' : 'FALSE',
					$MaxFileSize,
					$MaxCourseSize,
					$MaxCourseFloat ? $MaxCourseFloat : 2097152,
					"'".implode("','", $IllegalExtentions)."'",
					SITE_NAME,
					defined('TABLE_PREFIX') ? TABLE_PREFIX : '',
					$_POST['allow_backwards_compatibility'],
					$comments);
	} else {	
		$values = array(urldecode($_POST['step2']['db_login']),
					urldecode($_POST['step2']['db_password']),
					$_POST['step2']['db_host'],
					$_POST['step2']['db_port'],
					$_POST['step2']['db_name'],
					urldecode($_POST['step4']['admin_password']),
					urldecode($_POST['step4']['admin_email']),
					$_POST['step3']['email_notification'],
					$_POST['step3']['allow_instructor_requests'],
					$_POST['step3']['auto_approve_instructors'],
					$_POST['step3']['max_file_size'],
					$_POST['step3']['max_course_size'],
					$_POST['step3']['max_course_float'],
					urldecode($_POST['step3']['ill_ext']),
					urldecode($_POST['step3']['site_name']),
					$_POST['step2']['tb_prefix'],
					'FALSE',
					$comments);
	}

	$config_template = str_replace($tokens, $values, $config_template);

	if (!$handle = fopen($filename, 'wb')) {
         return 0;
    }
	ftruncate($handle,0);
    if (!fwrite($handle, $config_template, strlen($config_template))) {
		return 0;
    }
        
    fclose($handle);
	return 1;				
}

$config_template = "<"."?php 
/************************************************************************/
/* ATutor                                                               */
/************************************************************************/
/* Copyright (c) 2002-2003 by Greg Gay, Joel Kronenberg, Heidi Hazelton */
/* http://atutor.ca                                                     */
/*                                                                      */
/* This program is free software. You can redistribute it and/or        */
/* modify it under the terms of the GNU General Public License          */
/* as published by the Free Software Foundation.                        */
/************************************************************************/
{GENERATED_COMMENTS}
/************************************************************************/
/*              DO NOT EDIT THIS FILE DIRECTLY!                         */
/*                                                                      */
/************************************************************************/

/* the database user name                                               */
define('DB_USER',                      '{USER}');

/* the database password                                                */
define('DB_PASSWORD',                  '{PASSWORD}');

/* the database host                                                    */
define('DB_HOST',                      '{HOST}');

/* the database tcp/ip port                                             */
define('DB_PORT',                      '{PORT}');

/* the database name                                                    */
define('DB_NAME',                      '{DBNAME}');

/* The prefix to add to table names to avoid conflicts with existing    */
/* tables. Default: AT_                                                 */
define('TABLE_PREFIX',                 '{TABLE_PREFIX}');

/* your (ATutor system admin) password to let you add new instructors   */
define('ADMIN_PASSWORD',               '{ADMIN_PASSWORD}');

/* your (admin) email address                                           */
define('ADMIN_EMAIL',                  '{ADMIN_EMAIL}');

/* do you want to receive emails when new instructor accounts           */
/* require approval                                                     */
define('EMAIL_NOTIFY',                 {EMAIL_NOTIFY});

/* allow regular account users to request their account to be           */
/* upgraded to instructor accounts.                                     */
define('ALLOW_INSTRUCTOR_REQUESTS',    {INSTRUCTOR_REQUESTS});

/* If ALLOW_INSTRUCTOR_REQUESTS is true then you can have the           */
/* requests approved instantly, otherwise each request will             */
/* have to be approved manually by the admin.                           */
define('AUTO_APPROVE_INSTRUCTORS',     {APPROVE_INSTRUCTORS});

/************************************************************************/
/* File manager options:                                                */

/* Default maximum allowable file size in Bytes to upload:              */
/* Will not override the upload_max_filesize in php.ini                 */
\$MaxFileSize   =   {MAX_FILE_SIZE}; /* 1 MB */

/* Default total maximum allowable course size in Bytes:                */
/* When this number is exceeded, no more uploads will be allowed        */
\$MaxCourseSize =  {MAX_COURSE_SIZE}; /* 10 MB */

/* Soft limit threshold:                                                */
/* How much a course can be over, while still allowing the              */
/* upload to finish.                                                    */
/* Therefore the real course limit is                                   */
/* \$MaxCourseSize + \$MaxCourseFloat, but when the float gets          */
/* used then no more uploads will be allowed.                           */
\$MaxCourseFloat =  {MAX_COURSE_FLOAT}; /* 2 MB */

/* Illegal file types, by extension. Include any extensions             */
/* you do not want to allow for uploading. (Just the extention          */
/* without the leading dot.)                                            */
\$IllegalExtentions = array({ILL_EXT});

/* The name of your course website.                                     */
/* Example: Acme University's Course Server                             */
/* Double quotes will have to be escaped with a slash: \\\".            */
define('SITE_NAME',                    \"{SITE_NAME}\");

/* Default language to use, if not browser-defined or                   */
/* user-defined. 'en' is always available. Any other language           */
/* specified must already exist in the database.                        */
/* Default language: en                                                 */
define('DEFAULT_LANGUAGE',             'en');

/* Where the cache directory should be created. On a Windows            */
/* machine the path should look like C:\Windows\temp\. Path             */
/* must end in a slash. The directory must already exist.               */
/* Make empty or comment out to disable cacheing.                       */
/* Back slashes must be escaped if at the end: ex: ..tmp\\');           */
//define('CACHE_DIR', '/dev/shm/');

/* If you upgrading from a previous version you may want to				*/ 
/* keep backwards compatability on. It is recommended that if			*/ 
/* you do not have too many content files then you should slowly		*/ 
/* convert your content to 1.3 and disable backwards					*/ 
/* compatability.														*/ 
/* Default: false														*/ 
define('BACKWARDS_COMPATIBILITY',       {BACKWARDS_COMPATIBILITY});

/* DO NOT ALTER THIS LAST LINE                                          */
define('AT_INSTALL', true);

?".">";

?>