<?php 
/************************************************************************/
/* ATutor                                                               */
/************************************************************************/
/* Copyright (c) 2002-2004 by Greg Gay, Joel Kronenberg, Heidi Hazelton */
/* http://atutor.ca                                                     */
/*                                                                      */
/* This program is free software. You can redistribute it and/or        */
/* modify it under the terms of the GNU General Public License          */
/* as published by the Free Software Foundation.                        */
/************************************************************************/
/* This file was generated by the ATutor 1.4.1 installation script.     */
/* File generated 2004-06-01 11:06:23                                   */
/************************************************************************/
/************************************************************************/

/* the database user name                                               */
define('DB_USER',                      'root');

/* the database password                                                */
define('DB_PASSWORD',                  'tydiutor');

/* the database host                                                    */
define('DB_HOST',                      'localhost');

/* the database tcp/ip port                                             */
define('DB_PORT',                      '3306');

/* the database name                                                    */
define('DB_NAME',                      'atutorsvn');

/* The prefix to add to table names to avoid conflicts with existing    */
/* tables. Default: AT_                                                 */
define('TABLE_PREFIX',                 'AT_');

/* your (ATutor system admin) username to let you add new instructors   */
define('ADMIN_USERNAME',               'admin');


/* your (ATutor system admin) password to let you add new instructors   */
define('ADMIN_PASSWORD',               'admin');

/* your (admin) email address                                           */
define('ADMIN_EMAIL',                  'bteh@hotmail.com');

/* do you want to receive emails when new instructor accounts           */
/* require approval                                                     */
define('EMAIL_NOTIFY',                 TRUE);

/* allow regular account users to request their account to be           */
/* upgraded to instructor accounts.                                     */
define('ALLOW_INSTRUCTOR_REQUESTS',    TRUE);

/* If ALLOW_INSTRUCTOR_REQUESTS is true then you can have the           */
/* requests approved instantly, otherwise each request will             */
/* have to be approved manually by the admin.                           */
define('AUTO_APPROVE_INSTRUCTORS',     FALSE);

/************************************************************************/
/* File manager options:                                                */

/* Default maximum allowable file size in Bytes to upload:              */
/* Will not override the upload_max_filesize in php.ini                 */
$MaxFileSize   =   1048576; /* 1 MB */

/* Default total maximum allowable course size in Bytes:                */
/* When this number is exceeded, no more uploads will be allowed        */
$MaxCourseSize =  10485760; /* 10 MB */

/* Soft limit threshold:                                                */
/* How much a course can be over, while still allowing the              */
/* upload to finish.                                                    */
/* Therefore the real course limit is                                   */
/* $MaxCourseSize + $MaxCourseFloat, but when the float gets          */
/* used then no more uploads will be allowed.                           */
$MaxCourseFloat =  2097152; /* 2 MB */

/* Illegal file types, by extension. Include any extensions             */
/* you do not want to allow for uploading. (Just the extention          */
/* without the leading dot.)                                            */
$IllegalExtentions = array('exe', 'asp', 'php', 'php3', 'bat', 'cgi', 'pl', 'com', 'vbs', 'reg', 'pcd', 'pif', 'scr', 'bas', 'inf', 'vb', 'vbe', 'wsc', 'wsf', 'wsh', );

/* The name of your course website.                                     */
/* Example: Acme University's Course Server                             */
/* Single quotes will have to be escaped with a slash: \'.              */
define('SITE_NAME',						'Course Server');

/* Public area variables.   */
/* Top left header image  - approximately w:230 x h:90					*/
/* Default: images/pub_default.jpg										*/	
define('HEADER_IMAGE',					'images/pub_default.jpg');

/* Top right logo default: images/at-logo.gif */
define('HEADER_LOGO',					'images/at-logo.gif');

/* link for the 'home' menu item.  Will not show if empty */
define('HOME_URL',						'');

/* Default language to use, if not browser-defined or                   */
/* user-defined. 'en' is always available. Any other language           */
/* specified must already exist in the database.                        */
/* Default language: en                                                 */
define('DEFAULT_LANGUAGE',             'en');

/* Where the cache directory should be created. On a Windows            */
/* machine the path should look like C:\Windows	emp\. Path             */
/* must end in a slash. The directory must already exist.               */
/* Make empty or comment out to disable cacheing.                       */
/* Back slashes must be escaped if at the end: ex: ..tmp\');           */
define('CACHE_DIR', '');

/* If you upgrading from a previous version you may want to				*/ 
/* keep backwards compatability on. It is recommended that if			*/ 
/* you do not have too many content files then you should slowly		*/ 
/* convert your content to 1.3 and disable backwards					*/ 
/* compatability.														*/ 
/* Default: false														*/ 
define('BACKWARDS_COMPATIBILITY',       FALSE);

/* Comma separated list of available theme directories.                 */
/* The themes are found under the /themes/ directory.                   */
/* The first theme is assumed to be the default.                        */
/* Example: 'default, peaches, lemons'                                  */
define('AVAILABLE_THEMES',	            'default');

/* Whether or not to use the default php.ini SMTP settings.             */
/* If false, then mail will try to be sent using sendmail.              */
define('MAIL_USE_SMTP', true);

/* ACollab integration constants.                                       */
/* Follow the instructions in ACollab's administration section under    */
/* Integrate ATutor.                                                    */
define('AC_PATH', 'http://titmouse.ic.utoronto.ca/acollab/');
define('AC_TABLE_PREFIX', 'AC_'); 


/* DO NOT ALTER THIS LAST LINE                                          */
define('AT_INSTALL', true);

?>