<?php
if (!defined('AT_INCLUDE_PATH')) { exit; }


/**
* Collects purchase information for PayPal -
* @access  public
* @param   int $payment_id		Payment Identifier generated by ATutor  
* @param   dbl $amount	the fee for the course
* @param   int $format_type		timestamp format, an AT_DATE constant
* @return  $_POST data		Pruchase information sent to Paypal
* @author  Greg Gay
*/

function paypal_print_form($payment_id, $amount, $course_id) {
	global $_config, $system_courses;
	if($_config['ec_gateway'] == 'PayPal'){
?>

		<form action="<?php echo $_config['ec_uri']; ?>" method="post">
			<input type="hidden" name="cmd" value="_xclick">
			<input type="hidden" name="business" value="<?php echo $_config['ec_vendor_id']; ?>">
			<input type="hidden" name="item_name" value="<?php echo htmlspecialchars($system_courses[$course_id]['title']); ?>">
			<input type="hidden" name="item_number" value="<?php echo $payment_id; ?>">
			<input type="hidden" name="amount" value="<?php echo $amount; ?>">
			<input type="hidden" name="page_style" value="Primary">
			<input type="hidden" name="no_shipping" value="0">
			<input type="hidden" name="return" value="<?php echo AT_BASE_HREF; ?>mods/ecomm/response_ipn.php?pid=<?php echo $payment_id; ?>">
			<input type="hidden" name="cancel_return" value="<?php echo AT_BASE_HREF; ?>mods/ecomm/response_ipn.php">
			<input type="hidden" name="no_note" value="1">
			<input type="hidden" name="currency_code" value="<?php echo $_config['ec_currency']; ?>">
			<input type="hidden" name="lc" value="CA">
			<input type="hidden" name="bn" value="PP-BuyNowBF">
			<input type="submit" src="https://www.sandbox.paypal.com/en_US/i/btn/x-click-but23.gif" border="0" name="submit" value="<?php echo _AT('ec_paybypaypal'); ?>">
			<img src="<?php echo $_base_path; ?>mods/ecomm/images/visa_42x27.gif" title="<?php echo _AT('ec_acceptvisa'); ?>" alt="<?php echo _AT('ec_acceptvisa'); ?>" align="middle" /> <img src="<?php echo $_base_path; ?>mods/ecomm/images/mc_42x27.gif" title="<?php echo _AT('ec_acceptmastercard'); ?>" alt="<?php echo _AT('ec_acceptmastercard'); ?>" align="middle" />
		</form>
	
	<?php
	}
}

function paypal_authenticate_user_response() {
	// nothing to do but set the feedback
	global $_config, $msg;
	if($_config['ec_gateway'] == 'PayPal'){ 
		if (isset($_GET['pid'], $_GET['amt'], $_GET['tx'], $_GET['sig'])) {
				approve_payment($_GET['pid'], $_GET['tx']);
				$msg->addFeedback('ACTION_COMPLETED_SUCCESSFULLY');
		}else{
				$msg->addError('EC_PAYMENT_FAILED');
		}
	}
}
function mirapay_print_form($payment_id, $amount, $course_id) {
	global $_config;
	if($_config['ec_gateway'] == 'MiraPay'){
		$mkey = md5($payment_id.$amount.$_config['ec_password']);
	?>
		<form method="post" action="<?php echo $_config['ec_uri']; ?>">
			<input type="hidden" name="MTID"        value="<?php echo $payment_id; ?>"/>
			<input type="hidden" name="Merchant_ID" value="<?php echo $_config['ec_vendor_id']; ?>"/>
			<input type="hidden" name="MKEY"        value="<?php echo $mkey; ?>"/>
			<input type="hidden" name="Amount1"     value="<?php echo $amount; ?>"/>
			<input type="hidden" name="SuccessURL"  value="<?php echo AT_BASE_HREF; ?>mods/ecomm/response_user.php"/>
			<input type="hidden" name="FailURL"     value="<?php echo AT_BASE_HREF; ?>mods/ecomm/response_user.php"/>
			<input type="hidden" name="Currency"    value="<?php echo $_config['ec_currency'];  ?>"/>
			<input type="submit" name="confirm" class="button" value="<?php echo _AT('ec_paybycredit'); ?>"/> 
			<img src="<?php echo $_base_path; ?>mods/ecomm/images/visa_42x27.gif" title="<?php echo _AT('ec_acceptvisa'); ?>" alt="<?php echo _AT('ec_acceptvisa'); ?>" align="middle" /> <img src="<?php echo $_base_path; ?>mods/ecomm/images/mc_42x27.gif" title="<?php echo _AT('ec_acceptmastercard'); ?>" alt="<?php echo _AT('ec_acceptmastercard'); ?>" align="middle" />
		</form>
	<?php
	}
}

function mirapay_authenticate_ipn() {
	// nothing to do
}

function mirapay_authenticate_user_response( ) {
	if (isset($_GET['MTID'], $_GET['Amount1'], $_GET['MiraID'], $_GET['Response'])) {
		global $_config, $msg;
		$response_hash = md5($_GET['MTID'] . $_GET['Amount1'] . $_GET['MiraID'] . $_GET['Response'] . $_config['ec_password']);
		if ($response_hash == $_GET['MKEY'] && !strcasecmp($_GET['Response'], 'APPROVED')) {
			approve_payment($_GET['MTID'], $_GET['MiraID']);
			$msg->addFeedback('ACTION_COMPLETED_SUCCESSFULLY');
		} else {
			$msg->addError('EC_PAYMENT_FAILED');
		}
	}
}

function approve_payment($payment_id, $transaction_id) {
	global $db, $system_courses, $_config, $msg;

	$sql = "UPDATE ".TABLE_PREFIX."payments SET transaction_id='$transaction_id', approved=1 WHERE payment_id=$payment_id";
	$result = mysql_query($sql, $db);

	// get the course_id for this transaction
	$sql = "SELECT course_id, member_id FROM ".TABLE_PREFIX."payments WHERE payment_id=$payment_id";
	$result = mysql_query($sql, $db);
	$row = mysql_fetch_assoc($result);
	$course_id = $row['course_id'];
	$member_id = $row['member_id'];

	$sql = "SELECT * FROM ".TABLE_PREFIX."ec_course_fees WHERE course_id=$course_id";
	if($result = mysql_query($sql,$db)){
	$course_fee_row = mysql_fetch_assoc($result);
	}
	if($course_fee_row['auto_approve'] == '1'){
		$sql = "UPDATE ".TABLE_PREFIX."course_enrollment SET approved='y' WHERE member_id=$member_id AND course_id=$course_id";
		mysql_query($sql, $db);
				$msg->addFeedback('EC_PAYMENT_CONFIRMED_AUTO');
	}else{

				$msg->addFeedback('EC_PAYMENT_CONFIRMED_MANUAL');
	}
	/// Get the course title
	$course_title  = $system_courses[$course_id]['title'];

	require(AT_INCLUDE_PATH . 'classes/phpmailer/atutormailer.class.php');
	// If auto email when payment is made, send an email to the instructor (maybe this should be an admin option)
	if ($course_fee_row['auto_email']) {

		/// Get the instructor's email address
		$sql = "SELECT email FROM ".TABLE_PREFIX."members WHERE member_id=".$system_courses[$course_id]['member_id'];
		$result = mysql_query($sql,$db);
		$row = mysql_fetch_assoc($result);
		$instructor_email = $row['email'];	
			
		$mail = new ATutorMailer;
		$mail->From     = $_config['contact_email'];
		$mail->AddAddress($instructor_email);
		$mail->Subject = _AT('ec_payment_made'); 
		$mail->Body    = _AT('ec_payment_mail_instruction', $course_title);
			
		if(!$mail->Send()) {
			$msg->printErrors('SENDING_ERROR');
			exit;
		}
		$mail->ClearAddresses();
	}

	if ($_config['ec_email_admin']) {
		/// Email Administrator  if set
		if ($_config['ec_email_admin']){
			if ($_config['ec_contact_email']){
				$contact_admin_email = $_config['ec_contact_email'];
			} else {
				$contact_admin_email = $_config['contact_email'];
			}
			$mail = new ATutorMailer;
			$mail->From     = $_config['contact_email'];
			$mail->AddAddress($contact_admin_email);
			$mail->Subject = _AT('ec_payment_made'); 
			$mail->Body    = _AT('ec_admin_payment_mail_instruction', $course_title);
			
			if (!$mail->Send()) {
				$msg->printErrors('SENDING_ERROR');
				exit;
			}
		}
	}
}

function check_payment_print_form($payment_id, $amount, $course_id){
global $db, $system_courses, $_config, $payment_id;

	if($_config['ec_contact_address'] != ''){
	echo _AT('or');
	?>
		<form  method="GET">
			<input type="hidden"  name="Amount1" value="<?php echo $amount; ?>">
			<input type="hidden"  name="payment_id" value="<?php echo $payment_id; ?>">
			<input class="button" type="submit" name="bycheque" value="<?php echo _AT('ec_paybycheque'); ?>" onclick="window.open('mods/ecomm/invoice.php?payment_id=<?php echo $payment_id.SEP; ?>course_title=<?php echo $system_courses[$course_id]['title'].SEP; ?>amount=<?php echo $amount; ?>','invwindow','height=425px, width=520px'); return false" /> 
		</form><br/><br />
	<?php }
}
?>